clone:
  git:
    image: plugins/git
    depth: 50
    tags: true
pipeline:
  ssh:
    image: appleboy/drone-ssh
    host: 139.59.123.108
    username: root
    password: [ ssh_password ]
    port: 22
    script:
      - echo hello
      - echo world
