clone:
  git:
    image: plugins/git
    depth: 50
    tags: true
pipeline:
#  frontend:
#    image: node:8.1.2
#    group: laravel
#    commands:
#      - node -v
#      - npm -v
#      - yarn --version
#      - yarn config set cache-folder .yarn-cache
#      - yarn install
#      - yarn run production

#  backend:
#    image: laradock/workspace:1.8-71
#    group: laravel
#    commands:
#      - php -v
#      - composer -V
#      - cp .env.example .env
#      - composer install --prefer-dist
#      - php artisan key:generate
#      - php artisan migrate
#      - ./vendor/bin/phpunit
  ssh:
    image: appleboy/drone-ssh
    host: 139.59.123.108
    username: root
    #secrets: [ ssh_password ]
    secrets:
      - source: sshpwd
        target: ssh_password
    port: 22
    script:
      - echo hello
      - echo world